config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'stories#index'
  devise_for :users, skip: :registrations
  authenticate :user do
    get 'stories', to: 'stories#index'
    get 'likedstories', to: 'stories#liked_stories'
    get '/story/:id', to: 'stories#show', as: :story
    post '/like/:id', to: 'stories#like', as: :like
    delete '/like/:id', to: 'stories#unlike', as: :unlike
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user

  validates :story_id, uniqueness: { scope: :user }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :likes

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/stories_controller.rb
# frozen_string_literal: true

class StoriesController < ApplicationController
  before_action :set_story_id, only: %i[like unlike show]

  def index
    data = StoryService.fetch_stories
    details = StoryService.fetch_stories_details(data)
    if data.blank?
      flash.now[:alert] = 'Something went wrong'
    else
      @stories = details
    end
  end

  def show
    data = StoryService.fetch_story(@story_id)
    if data.blank?
      flash.now[:alert] = 'Something went wrong'
    else
      @story = data
      @is_liked = current_user.likes.find_by(story_id: @story_id).present?
      @liked_by = Like.includes(:user).where(story_id: @story_id).map(&:user)
    end
  end

  def liked_stories
    @data =  Like.distinct.all.paginate(page: params[:page], per_page: 10)
    @stories = StoryService.fetch_stories_details(@data.pluck(:story_id).uniq)
  end

  def like
    current_user.likes.create(story_id: @story_id)
  end

  def unlike
    current_user.likes.find_by(story_id: @story_id)&.delete
  end

  private

  def set_story_id
    @story_id = params[:id]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .a.navbar-brand
    = link_to("Top News", user_signed_in? ? root_path : new_user_session_path , class: 'btn btn-outline-dark')
  %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavAltMarkup", "data-toggle" => "collapse", type: "button"}
    %span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse
    .navbar-nav
      .a.nav-item.nav-link.active
        - if user_signed_in?
          .d-flex.flex-row
            = link_to("Liked Stories", likedstories_path, class: 'btn btn-primary mr-4')
            = button_to("Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary')
        - else
          = link_to("Log In", new_user_session_path, class: 'btn btn-primary')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Top News
    %link{crossorigin: "anonymous", href: "https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css", integrity: "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", rel: "stylesheet"}/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .text-center
      %p.notice= notice
      %p.alert= alert
    = yield

app/views/stories/_liked_by.html.haml
#liked_by
  %h6.card-subtitle.mb-2.text-muted Liked by
  #users.ul.list-group.user_list
    - unless @liked_by.blank?
      - liked_by.each do |user|
        .li.list-group-item{id: "#{user.id}"}
          = user.full_name

app/views/stories/_stories.html.haml
- if stories.present?
  %table.table.table-bordered.table-condensed
    %tr
      %th.text-center #
      %th.text-center Title

    - stories.each do |story|
      %tr.text-center
        %td= story['id']
        %td= link_to story['title'], story_path(id: story['id'])

- else
  %h4.text-center No stories found

app/views/stories/index.html.haml
.d-flex.justify-content-center
  .sm-container
    %h1.text-center.mb-4 Welcome to Top News
    = render 'stories' , stories: @stories

app/views/stories/like.js.erb
$('#like').replaceWith($('<div id="like"><%= button_to 'Unlike', unlike_path(id: @story_id), remote: true, class: 'btn btn-danger mb-4', method: :delete %></div>'))
$('#users').append($('<div class="li list-group-item" id="<%=current_user.id%>"><%= current_user.full_name %></div>'))

app/views/stories/liked_stories.haml
.d-flex.justify-content-center
  .sm-container
    %h1.text-center.mb-4 Liked Stories
    = render 'stories' , stories: @stories
    .digg_pagination
      = will_paginate @data

app/views/stories/show.html.haml
- if @story.present?
  .d-flex.justify-content-center
    .card{style: "width: 18rem;"}
      .card-body
        .h5.card-title
          = link_to @story["title"], @story["url"]
        .h6.card-subtitle.mb-2.text-muted
          =  ("Author : #{@story["by"]}")
        #like
          - if !@is_liked
            = button_to 'Like', like_path(id: @story["id"]), remote: true, class: 'btn btn-primary mb-4'
          - else
            = button_to 'Unlike', unlike_path(id: @story["id"]), method: :delete, remote: true, class: 'btn btn-danger mb-4'
        = render 'liked_by' , liked_by: @liked_by

app/views/stories/unlike.js.erb
$('#like').replaceWith($('<div id="like"><%= button_to 'Like', like_path(id: @story_id), remote: true, class: 'btn btn-primary mb-4' %></div>'))
$("<%="##{current_user.id}"%>").remove()